# Site settings
title: 周一飞
baseurl: "/MySiteCN"
url: "https://fynnzhou.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: 周一飞
  desc: 你好！欢迎来到我的主页，我叫周一飞，励志成为一名优秀的量化研究员
  email: fynnzhou@outlook.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: fynnzhou
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# copyright
copy: © <!--copyyears--> deepit.at; Yifei Zhou.

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

